/*
 * SalaryProvider.java
 * This file was last modified at 2018.12.03 20:05 by Victor N. Skurikhin.
 * $Id$
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 */

package ru.otus.soap.wsclient.salary;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "SalaryProvider", targetNamespace = "http://salary.wservice.soap.otus.ru/")
@XmlSeeAlso({ObjectFactory.class})
public interface SalaryProvider
{
    /**
     * @return returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(
        localName = "getMaxSalary",
        targetNamespace = "http://salary.wservice.soap.otus.ru/",
        className = "ru.otus.soap.wsclient.salary.GetMaxSalary"
    )
    @ResponseWrapper(
        localName = "getMaxSalaryResponse",
        targetNamespace = "http://salary.wservice.soap.otus.ru/",
        className = "ru.otus.soap.wsclient.salary.GetMaxSalaryResponse"
    )
    @Action(
        input = "http://salary.wservice.soap.otus.ru/SalaryProvider/getMaxSalaryRequest",
        output = "http://salary.wservice.soap.otus.ru/SalaryProvider/getMaxSalaryResponse"
    )
    public long getMaxSalary();

    /**
     * @return returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(
        localName = "getAvgSalary",
        targetNamespace = "http://salary.wservice.soap.otus.ru/",
        className = "ru.otus.soap.wsclient.salary.GetAvgSalary"
    )
    @ResponseWrapper(
        localName = "getAvgSalaryResponse",
        targetNamespace = "http://salary.wservice.soap.otus.ru/",
        className = "ru.otus.soap.wsclient.salary.GetAvgSalaryResponse"
    )
    @Action(
        input = "http://salary.wservice.soap.otus.ru/SalaryProvider/getAvgSalaryRequest",
        output = "http://salary.wservice.soap.otus.ru/SalaryProvider/getAvgSalaryResponse"
    )
    public Double getAvgSalary();
}

/* vim: syntax=java:fileencoding=utf-8:fileformat=unix:tw=78:ts=4:sw=4:sts=4:et
 */
//EOF
