/*
 * SalaryWebService.java
 * This file was last modified at 29.11.18 11:17 by Victor N. Skurikhin.
 * $Id$
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 */

package ru.otus.soap.wsclient.salary;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalaryWebService", targetNamespace = "http://salary.wservice.soap.otus.ru/", wsdlLocation = "http://probook:8080/homework9/SalaryWebService?wsdl")
public class SalaryWebService
    extends Service
{

    private final static URL SALARYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALARYWEBSERVICE_EXCEPTION;
    private final static QName SALARYWEBSERVICE_QNAME = new QName("http://salary.wservice.soap.otus.ru/", "SalaryWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://probook:8080/homework9/SalaryWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALARYWEBSERVICE_WSDL_LOCATION = url;
        SALARYWEBSERVICE_EXCEPTION = e;
    }

    public SalaryWebService() {
        super(__getWsdlLocation(), SALARYWEBSERVICE_QNAME);
    }

    public SalaryWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALARYWEBSERVICE_QNAME, features);
    }

    public SalaryWebService(URL wsdlLocation) {
        super(wsdlLocation, SALARYWEBSERVICE_QNAME);
    }

    public SalaryWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALARYWEBSERVICE_QNAME, features);
    }

    public SalaryWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalaryWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalaryProvider
     */
    @WebEndpoint(name = "SalaryProviderPort")
    public SalaryProvider getSalaryProviderPort() {
        return super.getPort(new QName("http://salary.wservice.soap.otus.ru/", "SalaryProviderPort"), SalaryProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalaryProvider
     */
    @WebEndpoint(name = "SalaryProviderPort")
    public SalaryProvider getSalaryProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://salary.wservice.soap.otus.ru/", "SalaryProviderPort"), SalaryProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALARYWEBSERVICE_EXCEPTION!= null) {
            throw SALARYWEBSERVICE_EXCEPTION;
        }
        return SALARYWEBSERVICE_WSDL_LOCATION;
    }

}
