DROP TABLE IF EXISTS dept_directory CASCADE;
DROP TABLE IF EXISTS emp_registry CASCADE;
DROP TABLE IF EXISTS statistic CASCADE;
DROP TABLE IF EXISTS user_groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP SEQUENCE IF EXISTS dept_id_seq;
DROP SEQUENCE IF EXISTS emp_id_seq;
DROP SEQUENCE IF EXISTS group_id_seq;
DROP SEQUENCE IF EXISTS statistic_id_seq;
DROP SEQUENCE IF EXISTS user_id_seq;
