/*
 * DailyInfoSoap.java
 * This file was last modified at 2018.12.03 20:05 by Victor N. Skurikhin.
 * $Id$
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 */

package ru.otus.soap.wsclient.cbr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "DailyInfoSoap", targetNamespace = "http://web.cbr.ru/")
@XmlSeeAlso({ObjectFactory.class})
public interface DailyInfoSoap
{
    /**
     * Сальдо операций ЦБ РФ по предоставлению/абсорбированию ликвидности
     * (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SaldoXMLResponse.SaldoXMLResult
     */
    @WebMethod(operationName = "SaldoXML", action = "http://web.cbr.ru/SaldoXML")
    @WebResult(name = "SaldoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SaldoXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SaldoXML"
    )
    @ResponseWrapper(
        localName = "SaldoXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SaldoXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.SaldoXMLResponse.SaldoXMLResult saldoXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставка ROISfix (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.ROISfixXMLResponse.ROISfixXMLResult
     */
    @WebMethod(operationName = "ROISfixXML", action = "http://web.cbr.ru/ROISfixXML")
    @WebResult(name = "ROISfixXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "ROISfixXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ROISfixXML"
    )
    @ResponseWrapper(
        localName = "ROISfixXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ROISfixXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.ROISfixXMLResponse.ROISfixXMLResult roiSfixXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставка Ruonia (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.RuoniaXMLResponse.RuoniaXMLResult
     */
    @WebMethod(operationName = "RuoniaXML", action = "http://web.cbr.ru/RuoniaXML")
    @WebResult(name = "RuoniaXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "RuoniaXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RuoniaXML"
    )
    @ResponseWrapper(
        localName = "RuoniaXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RuoniaXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.RuoniaXMLResponse.RuoniaXMLResult ruoniaXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Депозиты банков в Банке России (млн. руб) (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.OstatDepoXMLResponse.OstatDepoXMLResult
     */
    @WebMethod(operationName = "OstatDepoXML", action = "http://web.cbr.ru/OstatDepoXML")
    @WebResult(name = "OstatDepoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "OstatDepoXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDepoXML"
    )
    @ResponseWrapper(
        localName = "OstatDepoXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDepoXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.OstatDepoXMLResponse.OstatDepoXMLResult ostatDepoXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Данные по интервенциям Банка России на внутреннем валютном рынке
     * - Ежедневные значения (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.ValIntDayXMLResponse.ValIntDayXMLResult
     */
    @WebMethod(operationName = "ValIntDayXML", action = "http://web.cbr.ru/ValIntDayXML")
    @WebResult(name = "ValIntDayXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "ValIntDayXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ValIntDayXML"
    )
    @ResponseWrapper(
        localName = "ValIntDayXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ValIntDayXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.ValIntDayXMLResponse.ValIntDayXMLResult valIntDayXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Данные по интервенциям Банка России на внутреннем валютном рынке
     * - Ежедневные значения
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.ValIntDayResponse.ValIntDayResult
     */
    @WebMethod(operationName = "ValIntDay", action = "http://web.cbr.ru/ValIntDay")
    @WebResult(name = "ValIntDayResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "ValIntDay",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ValIntDay"
    )
    @ResponseWrapper(
        localName = "ValIntDayResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ValIntDayResponse"
    )
    public ru.otus.soap.wsclient.cbr.ValIntDayResponse.ValIntDayResult valIntDay(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Депозиты банков в Банке России (млн. руб)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.OstatDepoResponse.OstatDepoResult
     */
    @WebMethod(operationName = "OstatDepo", action = "http://web.cbr.ru/OstatDepo")
    @WebResult(name = "OstatDepoResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "OstatDepo",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDepo"
    )
    @ResponseWrapper(
        localName = "OstatDepoResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDepoResponse"
    )
    public ru.otus.soap.wsclient.cbr.OstatDepoResponse.OstatDepoResult ostatDepo(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставка ROISfix (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.ROISfixResponse.ROISfixResult
     */
    @WebMethod(operationName = "ROISfix", action = "http://web.cbr.ru/ROISfix")
    @WebResult(name = "ROISfixResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "ROISfix",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ROISfix"
    )
    @ResponseWrapper(
        localName = "ROISfixResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.ROISfixResponse"
    )
    public ru.otus.soap.wsclient.cbr.ROISfixResponse.ROISfixResult roiSfix(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставка RUONIA (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.RuoniaResponse.RuoniaResult
     */
    @WebMethod(operationName = "Ruonia", action = "http://web.cbr.ru/Ruonia")
    @WebResult(name = "RuoniaResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Ruonia",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Ruonia"
    )
    @ResponseWrapper(
        localName = "RuoniaResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RuoniaResponse"
    )
    public ru.otus.soap.wsclient.cbr.RuoniaResponse.RuoniaResult ruonia(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Международные резервы Российской Федерации, еженедельные значения
     * (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.Mrrf7DResponse.Mrrf7DResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrf7D")
    @WebResult(name = "mrrf7DResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "mrrf7D",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Mrrf7D"
    )
    @ResponseWrapper(
        localName = "mrrf7DResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Mrrf7DResponse"
    )
    public ru.otus.soap.wsclient.cbr.Mrrf7DResponse.Mrrf7DResult mrrf7D(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Международные резервы Российской Федерации, еженедельные значения
     * (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.Mrrf7DXMLResponse.Mrrf7DXMLResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrf7DXML")
    @WebResult(name = "mrrf7DXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "mrrf7DXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Mrrf7DXML"
    )
    @ResponseWrapper(
        localName = "mrrf7DXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Mrrf7DXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.Mrrf7DXMLResponse.Mrrf7DXMLResult mrrf7DXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Задолженность кредитных организаций перед Банком России по операциям РЕПО
     * в иностранной валюте (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.RepoDebtUSDResponse.RepoDebtUSDResult
     */
    @WebMethod(operationName = "RepoDebtUSD", action = "http://web.cbr.ru/RepoDebtUSD")
    @WebResult(name = "RepoDebtUSDResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "RepoDebtUSD",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtUSD"
    )
    @ResponseWrapper(
        localName = "RepoDebtUSDResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtUSDResponse"
    )
    public ru.otus.soap.wsclient.cbr.RepoDebtUSDResponse.RepoDebtUSDResult repoDebtUSD(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Задолженность кредитных организаций перед Банком России по операциям РЕПО
     * в иностранной валюте  (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.RepoDebtUSDXMLResponse.RepoDebtUSDXMLResult
     */
    @WebMethod(operationName = "RepoDebtUSDXML", action = "http://web.cbr.ru/RepoDebtUSDXML")
    @WebResult(name = "RepoDebtUSDXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "RepoDebtUSDXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtUSDXML"
    )
    @ResponseWrapper(
        localName = "RepoDebtUSDXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtUSDXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.RepoDebtUSDXMLResponse.RepoDebtUSDXMLResult repoDebtUSDXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Международные резервы Российской Федерации, ежемесячные значения
     * (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.MrrfResponse.MrrfResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrf")
    @WebResult(name = "mrrfResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "mrrf",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Mrrf"
    )
    @ResponseWrapper(
        localName = "mrrfResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MrrfResponse"
    )
    public ru.otus.soap.wsclient.cbr.MrrfResponse.MrrfResult mrrf(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Международные резервы Российской Федерации, ежемесячные значения
     * (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.MrrfXMLResponse.MrrfXMLResult
     */
    @WebMethod(action = "http://web.cbr.ru/mrrfXML")
    @WebResult(name = "mrrfXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "mrrfXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MrrfXML"
    )
    @ResponseWrapper(
        localName = "mrrfXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MrrfXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.MrrfXMLResponse.MrrfXMLResult mrrfXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Сальдо операций ЦБ РФ по предоставлению/абсорбированию ликвидности
     * (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SaldoResponse.SaldoResult
     */
    @WebMethod(operationName = "Saldo", action = "http://web.cbr.ru/Saldo")
    @WebResult(name = "SaldoResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Saldo",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Saldo"
    )
    @ResponseWrapper(
        localName = "SaldoResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SaldoResponse"
    )
    public ru.otus.soap.wsclient.cbr.SaldoResponse.SaldoResult saldo(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Получение новостей сервера (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.NewsInfoXMLResponse.NewsInfoXMLResult
     */
    @WebMethod(operationName = "NewsInfoXML", action = "http://web.cbr.ru/NewsInfoXML")
    @WebResult(name = "NewsInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "NewsInfoXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.NewsInfoXML"
    )
    @ResponseWrapper(
        localName = "NewsInfoXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.NewsInfoXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.NewsInfoXMLResponse.NewsInfoXMLResult newsInfoXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Операции на открытом рынке (как XMLDocument)
     *
     * @return returns ru.otus.soap.wsclient.cbr.OmodInfoXMLResponse.OmodInfoXMLResult
     */
    @WebMethod(operationName = "OmodInfoXML", action = "http://web.cbr.ru/OmodInfoXML")
    @WebResult(name = "OmodInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "OmodInfoXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OmodInfoXML"
    )
    @ResponseWrapper(
        localName = "OmodInfoXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OmodInfoXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.OmodInfoXMLResponse.OmodInfoXMLResult omodInfoXML();

    /**
     * Операции Банка России на рынке государственных ценных бумаг по поручению
     * Министерства финансов Российской Федерации (как DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.XVolResponse.XVolResult
     */
    @WebMethod(operationName = "XVol", action = "http://web.cbr.ru/XVol")
    @WebResult(name = "XVolResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "XVol",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.XVol"
    )
    @ResponseWrapper(
        localName = "XVolResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.XVolResponse"
    )
    public ru.otus.soap.wsclient.cbr.XVolResponse.XVolResult xVol(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Операции Банка России на рынке государственных ценных бумаг по поручению
     * Министерства финансов Российской Федерации  (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.XVolXMLResponse.XVolXMLResult
     */
    @WebMethod(operationName = "XVolXML", action = "http://web.cbr.ru/XVolXML")
    @WebResult(name = "XVolXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "XVolXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.XVolXML"
    )
    @ResponseWrapper(
        localName = "XVolXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.XVolXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.XVolXMLResponse.XVolXMLResult xVolXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar toDate);

    /**
     * Получение основной информации - Ставка рефинансирования, золотовалютные
     * резервы, денежная база, денежная масса (как XMLDocument)
     *
     * @return returns ru.otus.soap.wsclient.cbr.MainInfoXMLResponse.MainInfoXMLResult
     */
    @WebMethod(operationName = "MainInfoXML", action = "http://web.cbr.ru/MainInfoXML")
    @WebResult(name = "MainInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "MainInfoXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MainInfoXML"
    )
    @ResponseWrapper(
        localName = "MainInfoXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MainInfoXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.MainInfoXMLResponse.MainInfoXMLResult mainInfoXML();

    /**
     * Получение всей оперативной информации (XmlDocument) ver 26.01.2017
     *
     * @return returns ru.otus.soap.wsclient.cbr.AllDataInfoXMLResponse.AllDataInfoXMLResult
     */
    @WebMethod(operationName = "AllDataInfoXML", action = "http://web.cbr.ru/AllDataInfoXML")
    @WebResult(name = "AllDataInfoXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "AllDataInfoXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.AllDataInfoXML"
    )
    @ResponseWrapper(
        localName = "AllDataInfoXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.AllDataInfoXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.AllDataInfoXMLResponse.AllDataInfoXMLResult allDataInfoXML();

    /**
     * Получение новостей сервера (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.NewsInfoResponse.NewsInfoResult
     */
    @WebMethod(operationName = "NewsInfo", action = "http://web.cbr.ru/NewsInfo")
    @WebResult(name = "NewsInfoResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "NewsInfo",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.NewsInfo"
    )
    @ResponseWrapper(
        localName = "NewsInfoResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.NewsInfoResponse"
    )
    public ru.otus.soap.wsclient.cbr.NewsInfoResponse.NewsInfoResult newsInfo(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Задолженность кредитных организаций перед Банком России по сделкам
     * «валютный своп» (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapDayTotalResponse.SwapDayTotalResult
     */
    @WebMethod(operationName = "SwapDayTotal", action = "http://web.cbr.ru/SwapDayTotal")
    @WebResult(name = "SwapDayTotalResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapDayTotal",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDayTotal"
    )
    @ResponseWrapper(
        localName = "SwapDayTotalResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDayTotalResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapDayTotalResponse.SwapDayTotalResult swapDayTotal(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Задолженность кредитных организаций перед Банком России по сделкам
     * «валютный своп» (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapDayTotalXMLResponse.SwapDayTotalXMLResult
     */
    @WebMethod(operationName = "SwapDayTotalXML", action = "http://web.cbr.ru/SwapDayTotalXML")
    @WebResult(name = "SwapDayTotalXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapDayTotalXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDayTotalXML"
    )
    @ResponseWrapper(
        localName = "SwapDayTotalXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDayTotalXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapDayTotalXMLResponse.SwapDayTotalXMLResult swapDayTotalXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Валютный своп buy/sell overnight (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapDynamicXMLResponse.SwapDynamicXMLResult
     */
    @WebMethod(operationName = "SwapDynamicXML", action = "http://web.cbr.ru/SwapDynamicXML")
    @WebResult(name = "SwapDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapDynamicXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDynamicXML"
    )
    @ResponseWrapper(
        localName = "SwapDynamicXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDynamicXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapDynamicXMLResponse.SwapDynamicXMLResult swapDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Объем сделок «валютный своп» по продаже долларов США за рубли, заключенных
     * Банком России (XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolXMLResponse.SwapInfoSellUSDVolXMLResult
     */
    @WebMethod(operationName = "SwapInfoSellUSDVolXML", action = "http://web.cbr.ru/SwapInfoSellUSDVolXML")
    @WebResult(name = "SwapInfoSellUSDVolXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapInfoSellUSDVolXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolXML"
    )
    @ResponseWrapper(
        localName = "SwapInfoSellUSDVolXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolXMLResponse.SwapInfoSellUSDVolXMLResult swapInfoSellUSDVolXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Объем сделок «валютный своп» по продаже долларов США за рубли,
     * заключенных Банком России (DataSet) ver 21.11.2014
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolResponse.SwapInfoSellUSDVolResult
     */
    @WebMethod(operationName = "SwapInfoSellUSDVol", action = "http://web.cbr.ru/SwapInfoSellUSDVol")
    @WebResult(name = "SwapInfoSellUSDVolResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapInfoSellUSDVol",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVol"
    )
    @ResponseWrapper(
        localName = "SwapInfoSellUSDVolResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapInfoSellUSDVolResponse.SwapInfoSellUSDVolResult swapInfoSellUSDVol(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Условия заключения сделок «валютный своп» по продаже долларов США за рубли
     * (DataSet) ver 18.09.2014
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapInfoSellUSDResponse.SwapInfoSellUSDResult
     */
    @WebMethod(operationName = "SwapInfoSellUSD", action = "http://web.cbr.ru/SwapInfoSellUSD")
    @WebResult(name = "SwapInfoSellUSDResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapInfoSellUSD",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSD"
    )
    @ResponseWrapper(
        localName = "SwapInfoSellUSDResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapInfoSellUSDResponse.SwapInfoSellUSDResult swapInfoSellUSD(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar toDate);

    /**
     * Условия заключения сделок «валютный своп» по продаже долларов США
     * за рубли (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapInfoSellUSDXMLResponse.SwapInfoSellUSDXMLResult
     */
    @WebMethod(operationName = "SwapInfoSellUSDXML", action = "http://web.cbr.ru/SwapInfoSellUSDXML")
    @WebResult(name = "SwapInfoSellUSDXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapInfoSellUSDXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDXML"
    )
    @ResponseWrapper(
        localName = "SwapInfoSellUSDXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapInfoSellUSDXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapInfoSellUSDXMLResponse.SwapInfoSellUSDXMLResult swapInfoSellUSDXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Стоимость бивалютной корзины (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.BiCurBaseXMLResponse.BiCurBaseXMLResult
     */
    @WebMethod(operationName = "BiCurBaseXML", action = "http://web.cbr.ru/BiCurBaseXML")
    @WebResult(name = "BiCurBaseXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "BiCurBaseXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBaseXML"
    )
    @ResponseWrapper(
        localName = "BiCurBaseXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBaseXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.BiCurBaseXMLResponse.BiCurBaseXMLResult biCurBaseXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Стоимость бивалютной корзины (DataSet) ver 03.12.2014
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.BiCurBaseResponse.BiCurBaseResult
     */
    @WebMethod(operationName = "BiCurBase", action = "http://web.cbr.ru/BiCurBase")
    @WebResult(name = "BiCurBaseResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "BiCurBase",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBase"
    )
    @ResponseWrapper(
        localName = "BiCurBaseResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBaseResponse"
    )
    public ru.otus.soap.wsclient.cbr.BiCurBaseResponse.BiCurBaseResult biCurBase(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Структура бивалютной корзины  (как xmlDocument)
     *
     * @return returns ru.otus.soap.wsclient.cbr.BiCurBacketXMLResponse.BiCurBacketXMLResult
     */
    @WebMethod(operationName = "BiCurBacketXML", action = "http://web.cbr.ru/BiCurBacketXML")
    @WebResult(name = "BiCurBacketXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "BiCurBacketXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBacketXML"
    )
    @ResponseWrapper(
        localName = "BiCurBacketXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBacketXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.BiCurBacketXMLResponse.BiCurBacketXMLResult biCurBacketXML();

    /**
     * Структура бивалютной корзины  (DataSet) ver 03.12.2014
     *
     * @return returns ru.otus.soap.wsclient.cbr.BiCurBacketResponse.BiCurBacketResult
     */
    @WebMethod(operationName = "BiCurBacket", action = "http://web.cbr.ru/BiCurBacket")
    @WebResult(name = "BiCurBacketResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "BiCurBacket",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBacket"
    )
    @ResponseWrapper(
        localName = "BiCurBacketResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BiCurBacketResponse"
    )
    public ru.otus.soap.wsclient.cbr.BiCurBacketResponse.BiCurBacketResult biCurBacket();

    /**
     * Условия заключения сделок «валютный своп» по покупке долларов США и евро за рубли (DataSet) ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapDynamicResponse.SwapDynamicResult
     */
    @WebMethod(operationName = "SwapDynamic", action = "http://web.cbr.ru/SwapDynamic")
    @WebResult(name = "SwapDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapDynamic",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDynamic"
    )
    @ResponseWrapper(
        localName = "SwapDynamicResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapDynamicResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapDynamicResponse.SwapDynamicResult swapDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Объем сделок 'валютный своп' Банка России (DataSet) ver 03.04.2014
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapMonthTotalResponse.SwapMonthTotalResult
     */
    @WebMethod(operationName = "SwapMonthTotal", action = "http://web.cbr.ru/SwapMonthTotal")
    @WebResult(name = "SwapMonthTotalResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapMonthTotal",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapMonthTotal"
    )
    @ResponseWrapper(
        localName = "SwapMonthTotalResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapMonthTotalResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapMonthTotalResponse.SwapMonthTotalResult swapMonthTotal(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Объем сделок 'валютный своп' Банка России (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.SwapMonthTotalXMLResponse.SwapMonthTotalXMLResult
     */
    @WebMethod(operationName = "SwapMonthTotalXML", action = "http://web.cbr.ru/SwapMonthTotalXML")
    @WebResult(name = "SwapMonthTotalXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "SwapMonthTotalXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapMonthTotalXML"
    )
    @ResponseWrapper(
        localName = "SwapMonthTotalXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.SwapMonthTotalXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.SwapMonthTotalXMLResponse.SwapMonthTotalXMLResult swapMonthTotalXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставки межбанковского кредитного рынка  (DataSet) ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.MKRResponse.MKRResult
     */
    @WebMethod(operationName = "MKR", action = "http://web.cbr.ru/MKR")
    @WebResult(name = "MKRResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "MKR",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MKR"
    )
    @ResponseWrapper(
        localName = "MKRResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MKRResponse"
    )
    public ru.otus.soap.wsclient.cbr.MKRResponse.MKRResult mkr(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставки межбанковского кредитного рынка (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.MKRXMLResponse.MKRXMLResult
     */
    @WebMethod(operationName = "MKRXML", action = "http://web.cbr.ru/MKRXML")
    @WebResult(name = "MKRXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "MKRXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MKRXML"
    )
    @ResponseWrapper(
        localName = "MKRXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.MKRXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.MKRXMLResponse.MKRXMLResult mkrxml(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Требования Банка России к кредитным организациям (DataSet) ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.DVResponse.DVResult
     */
    @WebMethod(operationName = "DV", action = "http://web.cbr.ru/DV")
    @WebResult(name = "DVResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "DV",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DV"
    )
    @ResponseWrapper(
        localName = "DVResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DVResponse"
    )
    public ru.otus.soap.wsclient.cbr.DVResponse.DVResult dv(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Требования Банка России к кредитным организациям (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.DVXMLResponse.DVXMLResult
     */
    @WebMethod(operationName = "DVXML", action = "http://web.cbr.ru/DVXML")
    @WebResult(name = "DVXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "DVXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DVXML"
    )
    @ResponseWrapper(
        localName = "DVXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DVXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.DVXMLResponse.DVXMLResult dvxml(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Задолженность кредитных организаций перед Банком России по операциям
     * прямого РЕПО (DataSet) ver 18.06.2014
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.RepoDebtResponse.RepoDebtResult
     */
    @WebMethod(operationName = "Repo_debt", action = "http://web.cbr.ru/Repo_debt")
    @WebResult(name = "Repo_debtResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Repo_debt",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebt"
    )
    @ResponseWrapper(
        localName = "Repo_debtResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtResponse"
    )
    public ru.otus.soap.wsclient.cbr.RepoDebtResponse.RepoDebtResult repoDebt(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Задолженность кредитных организаций перед Банком России по операциям
     * прямого РЕПО (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.RepoDebtXMLResponse.RepoDebtXMLResult
     */
    @WebMethod(operationName = "Repo_debtXML", action = "http://web.cbr.ru/Repo_debtXML")
    @WebResult(name = "Repo_debtXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Repo_debtXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtXML"
    )
    @ResponseWrapper(
        localName = "Repo_debtXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.RepoDebtXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.RepoDebtXMLResponse.RepoDebtXMLResult repoDebtXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Отпускные цены Банка России на инвестиционные монеты (DataSet)
     * ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.CoinsBaseResponse.CoinsBaseResult
     */
    @WebMethod(operationName = "Coins_base", action = "http://web.cbr.ru/Coins_base")
    @WebResult(name = "Coins_baseResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Coins_base",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.CoinsBase"
    )
    @ResponseWrapper(
        localName = "Coins_baseResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.CoinsBaseResponse"
    )
    public ru.otus.soap.wsclient.cbr.CoinsBaseResponse.CoinsBaseResult coinsBase(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Отпускные цены Банка России на инвестиционные монеты (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.CoinsBaseXMLResponse.CoinsBaseXMLResult
     */
    @WebMethod(operationName = "Coins_baseXML", action = "http://web.cbr.ru/Coins_baseXML")
    @WebResult(name = "Coins_baseXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Coins_baseXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.CoinsBaseXML"
    )
    @ResponseWrapper(
        localName = "Coins_baseXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.CoinsBaseXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.CoinsBaseXMLResponse.CoinsBaseXMLResult coinsBaseXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Фиксинги на драгоценные металлы (DataSet) ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.FixingBaseResponse.FixingBaseResult
     */
    @WebMethod(operationName = "FixingBase", action = "http://web.cbr.ru/FixingBase")
    @WebResult(name = "FixingBaseResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "FixingBase",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.FixingBase"
    )
    @ResponseWrapper(
        localName = "FixingBaseResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.FixingBaseResponse"
    )
    public ru.otus.soap.wsclient.cbr.FixingBaseResponse.FixingBaseResult fixingBase(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Фиксинги на драгоценные металлы (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.FixingBaseXMLResponse.FixingBaseXMLResult
     */
    @WebMethod(operationName = "FixingBaseXML", action = "http://web.cbr.ru/FixingBaseXML")
    @WebResult(name = "FixingBaseXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "FixingBaseXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.FixingBaseXML"
    )
    @ResponseWrapper(
        localName = "FixingBaseXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.FixingBaseXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.FixingBaseXMLResponse.FixingBaseXMLResult fixingBaseXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставки по кредиту 'overnight' (DataSet) ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.OvernightResponse.OvernightResult
     */
    @WebMethod(operationName = "Overnight", action = "http://web.cbr.ru/Overnight")
    @WebResult(name = "OvernightResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Overnight",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Overnight"
    )
    @ResponseWrapper(
        localName = "OvernightResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OvernightResponse"
    )
    public ru.otus.soap.wsclient.cbr.OvernightResponse.OvernightResult overnight(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Ставки по кредиту 'overnight' (как xmlDocument
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.OvernightXMLResponse.OvernightXMLResult
     */
    @WebMethod(operationName = "OvernightXML", action = "http://web.cbr.ru/OvernightXML")
    @WebResult(name = "OvernightXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "OvernightXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OvernightXML")
    @ResponseWrapper(
        localName = "OvernightXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OvernightXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.OvernightXMLResponse.OvernightXMLResult overnightXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * База данных по размещению бюджетных средств на депозиты коммерческих
     * банков (DataSet) ver 31.07.2012
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.BauctionResponse.BauctionResult
     */
    @WebMethod(operationName = "Bauction", action = "http://web.cbr.ru/Bauction")
    @WebResult(name = "BauctionResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "Bauction",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.Bauction"
    )
    @ResponseWrapper(
        localName = "BauctionResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BauctionResponse"
    )
    public ru.otus.soap.wsclient.cbr.BauctionResponse.BauctionResult bauction(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * База данных по размещению бюджетных средств на депозиты коммерческих
     * банков (как xmlDocument
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.BauctionXMLResponse.BauctionXMLResult
     */
    @WebMethod(operationName = "BauctionXML", action = "http://web.cbr.ru/BauctionXML")
    @WebResult(name = "BauctionXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "BauctionXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BauctionXML"
    )
    @ResponseWrapper(
        localName = "BauctionXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.BauctionXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.BauctionXMLResponse.BauctionXMLResult bauctionXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Динамики ставок привлечения средств по депозитным операциям
     * (как xmlDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.DepoDynamicXMLResponse.DepoDynamicXMLResult
     */
    @WebMethod(operationName = "DepoDynamicXML", action = "http://web.cbr.ru/DepoDynamicXML")
    @WebResult(name = "DepoDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "DepoDynamicXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DepoDynamicXML"
    )
    @ResponseWrapper(
        localName = "DepoDynamicXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DepoDynamicXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.DepoDynamicXMLResponse.DepoDynamicXMLResult depoDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Динамика ставок привлечения средств по депозитным операциям (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.DepoDynamicResponse.DepoDynamicResult
     */
    @WebMethod(operationName = "DepoDynamic", action = "http://web.cbr.ru/DepoDynamic")
    @WebResult(name = "DepoDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "DepoDynamic",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DepoDynamic"
    )
    @ResponseWrapper(
        localName = "DepoDynamicResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DepoDynamicResponse"
    )
    public ru.otus.soap.wsclient.cbr.DepoDynamicResponse.DepoDynamicResult depoDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Динамики сведений об остатках средств на корреспондентских счетах
     * кредитных организаций (XMLDocument).
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.OstatDynamicXMLResponse.OstatDynamicXMLResult
     */
    @WebMethod(operationName = "OstatDynamicXML", action = "http://web.cbr.ru/OstatDynamicXML")
    @WebResult(name = "OstatDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "OstatDynamicXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDynamicXML"
    )
    @ResponseWrapper(
        localName = "OstatDynamicXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDynamicXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.OstatDynamicXMLResponse.OstatDynamicXMLResult ostatDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Динамики сведений об остатках средств на корреспондентских счетах
     * кредитных организаций (DataSet)!
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.OstatDynamicResponse.OstatDynamicResult
     */
    @WebMethod(operationName = "OstatDynamic", action = "http://web.cbr.ru/OstatDynamic")
    @WebResult(name = "OstatDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "OstatDynamic",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDynamic"
    )
    @ResponseWrapper(
        localName = "OstatDynamicResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.OstatDynamicResponse"
    )
    public ru.otus.soap.wsclient.cbr.OstatDynamicResponse.OstatDynamicResult ostatDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Динамика учетных цен драгоценных металлов (как XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.DragMetDynamicXMLResponse.DragMetDynamicXMLResult
     */
    @WebMethod(operationName = "DragMetDynamicXML", action = "http://web.cbr.ru/DragMetDynamicXML")
    @WebResult(name = "DragMetDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "DragMetDynamicXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DragMetDynamicXML"
    )
    @ResponseWrapper(
        localName = "DragMetDynamicXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DragMetDynamicXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.DragMetDynamicXMLResponse.DragMetDynamicXMLResult dragMetDynamicXML(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Динамика учетных цен драгоценных металлов (DataSet)
     *
     * @param fromDate
     * @param toDate
     * @return returns ru.otus.soap.wsclient.cbr.DragMetDynamicResponse.DragMetDynamicResult
     */
    @WebMethod(operationName = "DragMetDynamic", action = "http://web.cbr.ru/DragMetDynamic")
    @WebResult(name = "DragMetDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "DragMetDynamic",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DragMetDynamic"
    )
    @ResponseWrapper(
        localName = "DragMetDynamicResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.DragMetDynamicResponse"
    )
    public ru.otus.soap.wsclient.cbr.DragMetDynamicResponse.DragMetDynamicResult dragMetDynamic(
        @WebParam(name = "fromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate
    );

    /**
     * Последняя дата публикации курсов валют как DateTime (ежедневные валюты)
     *
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLatestDateTime", action = "http://web.cbr.ru/GetLatestDateTime")
    @WebResult(name = "GetLatestDateTimeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetLatestDateTime",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateTime"
    )
    @ResponseWrapper(
        localName = "GetLatestDateTimeResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateTimeResponse"
    )
    public XMLGregorianCalendar getLatestDateTime();

    /**
     * Последняя дата публикации курсов валют(ежемесячные валюты) - строка
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetLatestDate", action = "http://web.cbr.ru/GetLatestDate")
    @WebResult(name = "GetLatestDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetLatestDate",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDate"
    )
    @ResponseWrapper(
        localName = "GetLatestDateResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateResponse"
    )
    public String getLatestDate();

    /**
     * Последняя дата публикации курсов валют как DateTime (ежемесячные валюты)
     *
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLatestDateTimeSeld", action = "http://web.cbr.ru/GetLatestDateTimeSeld")
    @WebResult(name = "GetLatestDateTimeSeldResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetLatestDateTimeSeld",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateTimeSeld"
    )
    @ResponseWrapper(
        localName = "GetLatestDateTimeSeldResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateTimeSeldResponse"
    )
    public XMLGregorianCalendar getLatestDateTimeSeld();

    /**
     * Последняя дата публикации курсов валют (ежемесячные валюты)
     * - строка yyyyMMdd
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetLatestDateSeld", action = "http://web.cbr.ru/GetLatestDateSeld")
    @WebResult(name = "GetLatestDateSeldResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetLatestDateSeld",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateSeld"
    )
    @ResponseWrapper(
        localName = "GetLatestDateSeldResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestDateSeldResponse"
    )
    public String getLatestDateSeld();

    /**
     * Справочник по кодам валют (как XMLDocument)
     *
     * @param seld
     * @return returns ru.otus.soap.wsclient.cbr.EnumValutesXMLResponse.EnumValutesXMLResult
     */
    @WebMethod(operationName = "EnumValutesXML", action = "http://web.cbr.ru/EnumValutesXML")
    @WebResult(name = "EnumValutesXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "EnumValutesXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumValutesXML"
    )
    @ResponseWrapper(
        localName = "EnumValutesXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumValutesXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.EnumValutesXMLResponse.EnumValutesXMLResult enumValutesXML(
        @WebParam(name = "Seld", targetNamespace = "http://web.cbr.ru/") boolean seld
    );

    /**
     * Справочник по кодам валют (как DataSet)
     *
     * @param seld
     * @return returns ru.otus.soap.wsclient.cbr.EnumValutesResponse.EnumValutesResult
     */
    @WebMethod(operationName = "EnumValutes", action = "http://web.cbr.ru/EnumValutes")
    @WebResult(name = "EnumValutesResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "EnumValutes",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumValutes"
    )
    @ResponseWrapper(
        localName = "EnumValutesResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumValutesResponse"
    )
    public ru.otus.soap.wsclient.cbr.EnumValutesResponse.EnumValutesResult enumValutes(
        @WebParam(name = "Seld", targetNamespace = "http://web.cbr.ru/") boolean seld
    );

    /**
     * Последняя дата публикации редких валют от Thomson Reuters как DateTime
     * (ежемесячные валюты)
     *
     * @return returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLatestReutersDateTime", action = "http://web.cbr.ru/GetLatestReutersDateTime")
    @WebResult(name = "GetLatestReutersDateTimeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetLatestReutersDateTime",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestReutersDateTime"
    )
    @ResponseWrapper(
        localName = "GetLatestReutersDateTimeResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetLatestReutersDateTimeResponse"
    )
    public XMLGregorianCalendar getLatestReutersDateTime();

    /**
     * Справочник по кодам редких валют от Thomson Reuters (как XMLDocument)
     *
     * @return returns ru.otus.soap.wsclient.cbr.EnumReutersValutesXMLResponse.EnumReutersValutesXMLResult
     */
    @WebMethod(operationName = "EnumReutersValutesXML", action = "http://web.cbr.ru/EnumReutersValutesXML")
    @WebResult(name = "EnumReutersValutesXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "EnumReutersValutesXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumReutersValutesXML"
    )
    @ResponseWrapper(
        localName = "EnumReutersValutesXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumReutersValutesXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.EnumReutersValutesXMLResponse.EnumReutersValutesXMLResult enumReutersValutesXML();

    /**
     * Справочник по кодам редких валют от Thomson Reuters  (как DataSet)
     *
     * @return returns ru.otus.soap.wsclient.cbr.EnumReutersValutesResponse.EnumReutersValutesResult
     */
    @WebMethod(operationName = "EnumReutersValutes", action = "http://web.cbr.ru/EnumReutersValutes")
    @WebResult(name = "EnumReutersValutesResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "EnumReutersValutes",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumReutersValutes"
    )
    @ResponseWrapper(
        localName = "EnumReutersValutesResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.EnumReutersValutesResponse"
    )
    public ru.otus.soap.wsclient.cbr.EnumReutersValutesResponse.EnumReutersValutesResult enumReutersValutes();

    /**
     * Получение ежедневных курсов редких валют от Thomson Reuters (как XMLDocument)
     *
     * @param onDate
     * @return returns ru.otus.soap.wsclient.cbr.GetReutersCursOnDateXMLResponse.GetReutersCursOnDateXMLResult
     */
    @WebMethod(operationName = "GetReutersCursOnDateXML", action = "http://web.cbr.ru/GetReutersCursOnDateXML")
    @WebResult(name = "GetReutersCursOnDateXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetReutersCursOnDateXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursOnDateXML"
    )
    @ResponseWrapper(
        localName = "GetReutersCursOnDateXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursOnDateXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetReutersCursOnDateXMLResponse.GetReutersCursOnDateXMLResult
    getReutersCursOnDateXML(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar onDate
    );

    /**
     * Получение ежедневных курсов редких валют от Thomson Reuters (как DataSet)
     *
     * @param onDate
     * @return returns ru.otus.soap.wsclient.cbr.GetReutersCursOnDateResponse.GetReutersCursOnDateResult
     */
    @WebMethod(operationName = "GetReutersCursOnDate", action = "http://web.cbr.ru/GetReutersCursOnDate")
    @WebResult(name = "GetReutersCursOnDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetReutersCursOnDate",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursOnDate"
    )
    @ResponseWrapper(
        localName = "GetReutersCursOnDateResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursOnDateResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetReutersCursOnDateResponse.GetReutersCursOnDateResult getReutersCursOnDate(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar onDate
    );

    /**
     * Получение динамики ежедневных курсов редкой валюты от Thomson Reuters
     * (как XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @param numCode
     * @return returns ru.otus.soap.wsclient.cbr.GetReutersCursDynamicXMLResponse.GetReutersCursDynamicXMLResult
     */
    @WebMethod(operationName = "GetReutersCursDynamicXML", action = "http://web.cbr.ru/GetReutersCursDynamicXML")
    @WebResult(name = "GetReutersCursDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetReutersCursDynamicXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursDynamicXML"
    )
    @ResponseWrapper(
        localName = "GetReutersCursDynamicXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursDynamicXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetReutersCursDynamicXMLResponse.GetReutersCursDynamicXMLResult
    getReutersCursDynamicXML(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate,
        @WebParam(name = "NumCode", targetNamespace = "http://web.cbr.ru/") int numCode
    );

    /**
     * Получение динамики ежедневных курсов редкой валюты от Thomson Reuters
     * (как DataSet)
     *
     * @param fromDate
     * @param toDate
     * @param numCode
     * @return returns ru.otus.soap.wsclient.cbr.GetReutersCursDynamicResponse.GetReutersCursDynamicResult
     */
    @WebMethod(operationName = "GetReutersCursDynamic", action = "http://web.cbr.ru/GetReutersCursDynamic")
    @WebResult(name = "GetReutersCursDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetReutersCursDynamic",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursDynamic"
    )
    @ResponseWrapper(
        localName = "GetReutersCursDynamicResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetReutersCursDynamicResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetReutersCursDynamicResponse.GetReutersCursDynamicResult getReutersCursDynamic(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate,
        @WebParam(name = "NumCode", targetNamespace = "http://web.cbr.ru/") int numCode
    );

    /**
     * Получение динамики ежедневных курсов валюты (как XMLDocument)
     *
     * @param fromDate
     * @param toDate
     * @param valutaCode
     * @return returns ru.otus.soap.wsclient.cbr.GetCursDynamicXMLResponse.GetCursDynamicXMLResult
     */
    @WebMethod(operationName = "GetCursDynamicXML", action = "http://web.cbr.ru/GetCursDynamicXML")
    @WebResult(name = "GetCursDynamicXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetCursDynamicXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursDynamicXML"
    )
    @ResponseWrapper(
        localName = "GetCursDynamicXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursDynamicXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetCursDynamicXMLResponse.GetCursDynamicXMLResult getCursDynamicXML(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate,
        @WebParam(name = "ValutaCode", targetNamespace = "http://web.cbr.ru/") String valutaCode
    );

    /**
     * Получение динамики ежедневных курсов валюты (как DataSet)
     *
     * @param fromDate
     * @param toDate
     * @param valutaCode
     * @return returns ru.otus.soap.wsclient.cbr.GetCursDynamicResponse.GetCursDynamicResult
     */
    @WebMethod(operationName = "GetCursDynamic", action = "http://web.cbr.ru/GetCursDynamic")
    @WebResult(name = "GetCursDynamicResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetCursDynamic",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursDynamic"
    )
    @ResponseWrapper(
        localName = "GetCursDynamicResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursDynamicResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetCursDynamicResponse.GetCursDynamicResult getCursDynamic(
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar toDate,
        @WebParam(name = "ValutaCode", targetNamespace = "http://web.cbr.ru/") String valutaCode
    );

    /**
     * Получение ежедневных курсов валют (как XMLDocument)
     *
     * @param onDate
     * @return returns ru.otus.soap.wsclient.cbr.GetCursOnDateXMLResponse.GetCursOnDateXMLResult
     */
    @WebMethod(operationName = "GetCursOnDateXML", action = "http://web.cbr.ru/GetCursOnDateXML")
    @WebResult(name = "GetCursOnDateXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetCursOnDateXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursOnDateXML"
    )
    @ResponseWrapper(
        localName = "GetCursOnDateXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursOnDateXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetCursOnDateXMLResponse.GetCursOnDateXMLResult getCursOnDateXML(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar onDate
    );

    /**
     * Получение ежемесячных курсов валют !*устаревший! (как XMLDocument)
     *
     * @param onDate
     * @return returns ru.otus.soap.wsclient.cbr.GetSeldCursOnDateXMLResponse.GetSeldCursOnDateXMLResult
     */
    @WebMethod(operationName = "GetSeldCursOnDateXML", action = "http://web.cbr.ru/GetSeldCursOnDateXML")
    @WebResult(name = "GetSeldCursOnDateXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetSeldCursOnDateXML",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetSeldCursOnDateXML"
    )
    @ResponseWrapper(
        localName = "GetSeldCursOnDateXMLResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetSeldCursOnDateXMLResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetSeldCursOnDateXMLResponse.GetSeldCursOnDateXMLResult getSeldCursOnDateXML(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar onDate
    );

    /**
     * Получение ежемесячных курсов валют !*устаревший! (как DataSet)
     *
     * @param onDate
     * @return returns ru.otus.soap.wsclient.cbr.GetSeldCursOnDateResponse.GetSeldCursOnDateResult
     */
    @WebMethod(operationName = "GetSeldCursOnDate", action = "http://web.cbr.ru/GetSeldCursOnDate")
    @WebResult(name = "GetSeldCursOnDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetSeldCursOnDate",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetSeldCursOnDate"
    )
    @ResponseWrapper(
        localName = "GetSeldCursOnDateResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetSeldCursOnDateResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetSeldCursOnDateResponse.GetSeldCursOnDateResult getSeldCursOnDate(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar onDate
    );

    /**
     * Получение ежедневных курсов валют (как DataSet)
     *
     * @param onDate
     * @return returns ru.otus.soap.wsclient.cbr.GetCursOnDateResponse.GetCursOnDateResult
     */
    @WebMethod(operationName = "GetCursOnDate", action = "http://web.cbr.ru/GetCursOnDate")
    @WebResult(name = "GetCursOnDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(
        localName = "GetCursOnDate",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursOnDate"
    )
    @ResponseWrapper(
        localName = "GetCursOnDateResponse",
        targetNamespace = "http://web.cbr.ru/",
        className = "ru.otus.soap.wsclient.cbr.GetCursOnDateResponse"
    )
    public ru.otus.soap.wsclient.cbr.GetCursOnDateResponse.GetCursOnDateResult getCursOnDate(
        @WebParam(name = "On_date", targetNamespace = "http://web.cbr.ru/") XMLGregorianCalendar onDate
    );
}

/* vim: syntax=java:fileencoding=utf-8:fileformat=unix:tw=78:ts=4:sw=4:sts=4:et
 */
//EOF
