/*
 * CorporateTaxWebService.java
 * This file was last modified at 2018.12.03 20:05 by Victor N. Skurikhin.
 * $Id$
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 */

package ru.otus.soap.wsclient.corptax;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(
    name = "CorporateTaxWebService",
    targetNamespace = "http://corptax.wservice.soap.otus.ru/",
    wsdlLocation = "http://localhost:8080/homework9/CorporateTaxWebService?wsdl"
)
public class CorporateTaxWebService extends Service
{

    private final static URL CORPORATETAXWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CORPORATETAXWEBSERVICE_EXCEPTION;
    private final static QName CORPORATETAXWEBSERVICE_QNAME = new QName(
        "http://corptax.wservice.soap.otus.ru/",
        "CorporateTaxWebService"
    );

    static {
        URL url = null;
        WebServiceException e = null;

        try {
            url = new URL("http://localhost:8080/homework9/CorporateTaxWebService?wsdl");
        }
        catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }

        CORPORATETAXWEBSERVICE_WSDL_LOCATION = url;
        CORPORATETAXWEBSERVICE_EXCEPTION = e;
    }

    public CorporateTaxWebService()
    {
        super(__getWsdlLocation(), CORPORATETAXWEBSERVICE_QNAME);
    }

    public CorporateTaxWebService(WebServiceFeature... features)
    {
        super(__getWsdlLocation(), CORPORATETAXWEBSERVICE_QNAME, features);
    }

    public CorporateTaxWebService(URL wsdlLocation)
    {
        super(wsdlLocation, CORPORATETAXWEBSERVICE_QNAME);
    }

    public CorporateTaxWebService(URL wsdlLocation, WebServiceFeature... features)
    {
        super(wsdlLocation, CORPORATETAXWEBSERVICE_QNAME, features);
    }

    public CorporateTaxWebService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public CorporateTaxWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features)
    {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CorporateTaxProvider
     */
    @WebEndpoint(name = "CorporateTaxProviderPort")
    public CorporateTaxProvider getCorporateTaxProviderPort()
    {
        return super.getPort(
            new QName("http://corptax.wservice.soap.otus.ru/", "CorporateTaxProviderPort"),
            CorporateTaxProvider.class
        );
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature}
     *                 to configure on the proxy. Supported features not in the
     *                 <code>features</code> parameter will have their default values.
     * @return returns CorporateTaxProvider
     */
    @WebEndpoint(name = "CorporateTaxProviderPort")
    public CorporateTaxProvider getCorporateTaxProviderPort(WebServiceFeature... features)
    {
        return super.getPort(
            new QName("http://corptax.wservice.soap.otus.ru/", "CorporateTaxProviderPort"),
            CorporateTaxProvider.class,
            features
        );
    }

    private static URL __getWsdlLocation()
    {
        if (CORPORATETAXWEBSERVICE_EXCEPTION != null) {
            throw CORPORATETAXWEBSERVICE_EXCEPTION;
        }

        return CORPORATETAXWEBSERVICE_WSDL_LOCATION;
    }
}

/* vim: syntax=java:fileencoding=utf-8:fileformat=unix:tw=78:ts=4:sw=4:sts=4:et
 */
//EOF
